stages:
  - build
  - deploy

variables:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"

build_api:
  stage: build
  image: docker:26
  services:
    - docker:26-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Docker login with user: $DOCKER_USER"
  only:
    - main

build_web:
  stage: build
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - web/evidentfit-web/.next/cache
      - web/evidentfit-web/node_modules
  before_script:
    - cd web/evidentfit-web
    - npm ci --include=dev
  script:
    - npm run build
  artifacts:
    paths:
      - web/evidentfit-web/out
    expire_in: 1 week
  only:
    - main
    - tags

deploy_web:
  stage: deploy
  image: node:20
  needs:
    - build_web
  variables:
    SWA_CLI_TELEMETRY: "off"
  before_script:
    - npm i -g @azure/static-web-apps-cli
  script:
    - swa deploy ./web/evidentfit-web/out --deployment-token "$SWA_DEPLOYMENT_TOKEN"
  only:
    - main
    - tags