stages: [build, deploy]

variables:
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: "1"

build_api:
  stage: build
  image: docker:26
  services: [docker:26-dind]
  variables: { DOCKER_TLS_CERTDIR: "" }
  script:
    - echo "Docker login with user: $DOCKER_USER"
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - docker build -t justinmelunis/evidentfit-api:$CI_COMMIT_SHORT_SHA -f api/Dockerfile .
    - docker push justinmelunis/evidentfit-api:$CI_COMMIT_SHORT_SHA
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes: ["api/**/*", ".gitlab-ci.yml"]
  only:
    variables:
      - $DOCKER_USER
      - $DOCKER_PASS

build_web:
  stage: build
  image: node:20
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - web/evidentfit-web/.next/cache
      - web/evidentfit-web/node_modules
  before_script:
    - cd web/evidentfit-web
    - npm ci --include=dev
  script:
    # Build the Next.js app with static export
    - npm run build
  artifacts:
    paths:
      - web/evidentfit-web/out
    expire_in: 1 week
  only:
    - main
    - tags

deploy_web:
  stage: deploy
  image: node:20
  needs: [build_web]
  variables:
    SWA_CLI_TELEMETRY: "off"
  before_script:
    - npm i -g @azure/static-web-apps-cli
  script:
    # Deploy the exported site (static) from web/evidentfit-web/out
    - swa deploy ./web/evidentfit-web/out --deployment-token "$SWA_DEPLOYMENT_TOKEN"
  only:
    - main
    - tags
