version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3002
      - DEMO_USER=demo
      - DEMO_PW=demo123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build: ./web/evidentfit-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
      - NEXT_PUBLIC_DEMO_USER=demo
      - NEXT_PUBLIC_DEMO_PW=demo123
    depends_on:
      - api
    restart: unless-stopped

networks:
  default:
    name: evidentfit-network
