services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - AZURE_KEY_VAULT_URL=https://kv-evidentfit.vault.azure.net/
    env_file:
      - ./api/azure-openai.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  web:
    build:
      context: ./web/evidentfit-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
      - NEXT_PUBLIC_DEMO_USER=demo
      - NEXT_PUBLIC_DEMO_PW=demo123
    depends_on:
      - api
    restart: unless-stopped
