apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidentfit-api
  labels:
    app: evidentfit-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evidentfit-api
  template:
    metadata:
      labels:
        app: evidentfit-api
    spec:
      containers:
      - name: api
        image: evidentfit-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"
        - name: AZURE_KEY_VAULT_URL
          valueFrom:
            secretKeyRef:
              name: azure-keyvault-secrets
              key: vault-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: evidentfit-api-service
spec:
  selector:
    app: evidentfit-api
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidentfit-web
  labels:
    app: evidentfit-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evidentfit-web
  template:
    metadata:
      labels:
        app: evidentfit-web
    spec:
      containers:
      - name: web
        image: evidentfit-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_BASE
          value: "https://evidentfit-api.azurecontainerapps.io"
        - name: NEXT_PUBLIC_DEMO_USER
          value: "demo"
        - name: NEXT_PUBLIC_DEMO_PW
          value: "demo123"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: evidentfit-web-service
spec:
  selector:
    app: evidentfit-web
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
