[project]
name = "evidentfit_shared"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["httpx>=0.27"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
